# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        avatar_thumb:
            quality: 75
            filters:
                thumbnail: { size: [75, 75], mode: outbound }
#                background: { size: [80, 80], position: center, color: '#333' }
        trick_thumb:
            quality: 75
            filters:
                thumbnail: { size: [225, 112.5], mode: outbound }